server:
  port: 8080

spring:
  application:
    name: swagger
  datasource:
    url: jdbc:h2:mem:biblioteca
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true

