server:
  port: 8080

spring:
  application:
    name: swagger
  cloud:
    azure:
      keyvault:
        secret:
          property-source:
            - endpoint: ${AZURE_KEY_VAULT_URL}
  datasource:
    url: ${AZURE_DATABASE}
    username: ${AZURE_USER_DATABASE}
    password: ${AZURE_USER_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
azure:
  keyvault:
    tenant-id: ${AZURE_TENANT_ID}
logging:
  level:
    org.springframework.jdbc.core: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
#    operationsSorter: alpha # alfabético por defecto
#    operationsSorter: none # sin ordenación